data_items = {
        'basic_create_asset': {
            "channel": "mychannel",
            "msp": "Org1MSP",
            "orguid": "Org1_appuser",
            "assetid": "asset12",
            "title": "Large medical dataset",
            "size": 5,
            "owner": "Org1MSP",
            "value": 15,
            "publisher": "TRUSTS",
            "creator": "TRUSTS_RESEARCH",
            "contactPoint": "Joe Trusts",
            "keyword": "Medical",
            "authorisation": "OAuth",
            "dataAccess": "URL:www.example.com/data",
            "creationDate": "07/02/22",
            "license": "MIT",
            "format": ".csv:none:csv",
            "accessInterface": "Web:Local",
            "description": "A sample asset on the trusts platform",
        },
        'secure_transfer_asset': {
            "channel": "mychannel",
            "msp": "Org1MSP",
            "orguid": "Org1_appuser",
            "assetid": "asset12",
            "buyermsp": "Org2MSP",
            "title": "Large medical dataset",
            "size": 5,
            "publisher": "TRUSTS",
            "creator": "TRUSTS_RESEARCH",
            "contactPoint": "Joe Trusts",
            "keyword": "Medical",
            "authorisation": "OAuth",
            "dataAccess": "URL:www.example.com/data",
            "creationDate": "07/02/22",
            "license": "MIT",
            "format": ".csv:none:csv",
            "accessInterface": "Web:Local",
            "description": "A sample asset on the trusts platform",
            "salt": "3932",
            "price": 30,
            "tradeid": "21"
                }
}
